// Ping request
http://localhost:8080/ping


###
// Get success for user id 1
http://localhost:8080/users/1

###
// Get 400 for invalid number
http://localhost:8080/users/abc

###
// Get 404 for user not found
http://localhost:8080/users/111

###
// valid json
POST http://localhost:8080/users/

{
    "id" : 1,
    "first_name": "Rajesh",
    "last_name" : "Reddy",
    "email": "rajeshtech4b8@gmail.com"
}

###
// invalid email id
POST http://localhost:8080/users/

{
    "id" : 3,
    "first_name": "Rajesh",
    "last_name" : "Reddy",
    "email": "  test@test.COM  "
}


###
// invalid json
POST http://localhost:8080/users/

some text here 