// Ping request
http://localhost:8080/ping


###
// Get success for user id 123
http://localhost:8080/users/123

###
// Get 400 for invalid number
http://localhost:8080/users/abc

###
// Get 404 for user not found
http://localhost:8080/users/111

###
// valid json
POST http://localhost:8080/users/

{
    "first_name": "Rajesh",
    "last_name" : "Reddy",
    "email": "rajeshtech4b8@gmail.com"
}

###
// invalid json
POST http://localhost:8080/users/

some text here 